# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15  # Latest PostgreSQL version
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: etl_db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    volumes:
      - .:/app

volumes:
  pgdata:
